### ISSUE TITLE
Fix failing tests

### ISSUE THREAD

**Issue by codejockie** [codejockie/document-manager#47]
Most of the tests in the project are failing on Travis. I would appreciate your help fixing it.

**Comment by marchrius** [comment]
What is the expected behavior? In the `GET v1/users/:id` test the invalid id is `101243578787677` and not `101243578787677678575` as respectively `PUT` and `DELETE`. So first of all I would change this, at this point the `401` error code is genuine as the `id` variable is not a valid parameter format.

**Comment by codejockie** [comment]
Okay. If you need anything, kindly let me know.

**Comment by marchrius** [comment]
No sorry, I'm busy ATM.
